### ISSUE TITLE
ngrinder test 시작 오류

### ISSUE THREAD

**Issue by shimguh** [beyond-sw-camp/beyond-sw-camp-be01_4nd_mini-project#12]
## ngrinder test 시작 시 오류
- test 시작 시 Connection is not completed or cached files digest weren't received until 10 sec 에러 발생 후 종료
- 검색 결과 컨트롤러와 에이전트의 연결 문제인 것 같은데 컨트롤러에서 에이전트 정보가 잘 불러와짐

## 해결
- 에이전트와 연결은 되어 있지만 테스트하는 에이전트의 포트는 닫혀있는 상태였음
- 에이전트의 포트를 추가로 열었지만 여전히 에러 발생 후 종료
- 포트를 한번에 열지 않고 하나씩 열어서 해결

**Comment by papercrane55123** [comment]
혹시 아래와 같은 에러 발생하나요?
2024-02-28 17:18:37,353 ERROR agent daemon: Failed to connect to '/192.168.0.25:12003'
2024-02-28 17:18:37,354 INFO  agent daemon: Test shuts down.

**Comment by shimguh** [comment]
아니요 Connection is not completed or cached files digest weren't received until 10 sec 에러만 뜨면서 종료 되었습니다
포트를 추가해 주니까 해결 되었습니다

**Comment by papercrane55123** [comment]
![LGTM](https://i.lgtm.fun/2pn2.png)

**Comment by pySatellite** [comment]
해결 과정 까지 공유 감사드립니다.
