### ISSUE TITLE
nginx test 오류

### ISSUE THREAD

**Issue by ae-chae** [beyond-sw-camp/beyond-sw-camp-be01_4nd_mini-project#14]
- JAVA 17 버전으로 nGrinder 를 시도했을 때 Agent 실행과정에서 아래와 같은 에러가 발생
```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
```

**Comment by ae-chae** [comment]
JAVA 17 버전이 호환되지 않아 발생하는 에러

해결 방법 (택일)
- JAVA 11로 버전 바꾸기
- nGrinder-3.5.6으로 재설치 후 실행


11로 버전 바꾼 뒤 재부팅

**Comment by Afresh2** [comment]
해결완료!

**Comment by Jaelinny** [comment]
![LGTM](https://i.lgtm.fun/2pd6.gif)
