### ISSUE TITLE
3팀 : nGrinder 부하 테스트 문제 - Script error

### ISSUE THREAD

**Issue by pdh4869** [beyond-sw-camp/beyond-sw-camp-be01_4nd_mini-project#8]
- 로컬로 프로젝트 테스트를 했을 때 script error가 발생합니다
- user 수를 적게 잡아도 에러가 발생하여 바로 테스트가 종료되면서 500 Internal Server Error 발생하며 nGrinder 또한 로그아웃 됩니다
- script는 http://127.0.0.1:8080/ 혹은 http://127.0.0.1:8080/session-login/todo로 설정했습니다.

**Comment by pySatellite** [comment]
https://github.com/beyond-sw-camp/beyond-sw-camp-be01_4nd_mini-project/issues/7 관련 이슈로 어제 저녁 같이 해결한 사항로 이슈 종료합니다.
