### ISSUE TITLE
ngrinder docker 설치

### ISSUE THREAD

**Issue by minu1215** [beyond-sw-camp/beyond-sw-camp-be01_4nd_mini-project#9]
https://github.com/naver/ngrinder/wiki/Installation-Guide#install-controller

**Comment by minu1215** [comment]
https://hub.docker.com/r/ngrinder/controller/

**Comment by minu1215** [comment]
docker run -d -v ~/ngrinder-controller:/opt/ngrinder-controller --name controller -p 80:80 -p 16001:16001 -p 12000-12009:12000-12009 ngrinder/controller

-p 80:80 을 -p 8080:80 으로 수정

**Comment by minu1215** [comment]
docker desktop 실행해서 됐을 수도 있습니다

**Comment by pySatellite** [comment]
공유 감사드립니다.
